name: Build and Deploy to EdgeOne Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  NEXT_PUBLIC_SITE_URL: ''

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx edgeone pages deploy .next -n noan-blog -t "${{ secrets.EDGEONE_API_TOKEN }}" -e production
